# Generated by Django 4.0 on 2021-12-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='msg_sender', to='auth.user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='msg_target', to='auth.user')),
            ],
        ),
    ]
